collections:
  - name: infra.aap_utilities
  - name: infra.ee_utilities
  - name: infra.aap_configuration_extended
  - name: infra.aap_configuration
  - name: community.general
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.eda
  - name: ansible.controller
  - name: kubernetes.core

